#!/bin/dash

path=.pushy/main/commit_logs

# error if no directory found
if [ ! -d ".pushy" ]; then
	echo "pushy-log: error: pushy repository directory .pushy not found" 1>&2
	exit 1
fi

# prints nothing if there is no commit
if [ ! -f ".pushy/main/commit_logs" ]; then
	echo -n "" 
	exit 1
fi

# prints whole file after sorting it in reverse
grep "." "$path" | sort -r